# frozen_string_literal: true

require 'hphones/version'
require 'hphones/request'
require 'hphones/response'

require 'faraday'

##
# Base class for Hphones
#
class Hphones
  ROOT_PATH = 'api'

  attr_reader :api_key

  # @param host [String] the hostname of the Headphones server
  # @param port [String, Integer] the port of the Headphones server
  # @param api_key [String] the API key generated by Headphones
  # @param protocol [String] the protocol being used (usually 'http' or 'https')
  # @param http_root [String] the optional root path set in Headphones
  def initialize(host:, port:, api_key:, protocol: 'http', http_root: nil)
    @host = host
    @port = port
    @protocol = protocol
    @http_root = decorate_http_root(http_root)

    @api_key = api_key
  end

  # Connection and URL stuff

  def connection
    @connection ||= Faraday.new(url: url)
  end

  def url
    @url ||= "#{protocol}://#{host}:#{port}"
  end

  def base_path
    @base_path ||= "#{http_root}/#{ROOT_PATH}"
  end

  # Actions

  def get_artist(artist_id)
    request cmd: 'getArtist', id: artist_id
  end

  def find_artist(name)
    request cmd: 'findArtist', name: name
  end

  private

  attr_reader :host, :port, :protocol, :http_root

  def request(params = {})
    req = Hphones::Request.new(self)
    req.get params.merge(apikey: api_key)
  end

  def decorate_http_root(http_root)
    if http_root =~ %r{^\/} || http_root.nil?
      http_root
    else
      "/#{http_root}"
    end
  end
end
